import type { FreebuffSessionServerResponse } from '@codebuff/common/types/freebuff-session'

export type FreeSessionStatus = 'queued' | 'active'

/** Public state returned to CLI clients. Excludes `status: 'none'`, which is
 *  generated by the route handler when `getSessionState` returns null. */
export type SessionStateResponse = Exclude<FreebuffSessionServerResponse, { status: 'none' }>

export interface InternalSessionRow {
  user_id: string
  status: FreeSessionStatus
  active_instance_id: string
  queued_at: Date
  admitted_at: Date | null
  expires_at: Date | null
  created_at: Date
  updated_at: Date
}
