import type { FreebuffSessionServerResponse } from '@codebuff/common/types/freebuff-session'
import type {
  FreebuffCountryBlockReason,
  FreebuffIpPrivacySignal,
} from '@codebuff/common/types/freebuff-session'
import type { FreebuffAccessTier } from '@codebuff/common/constants/freebuff-models'
import type { FireworksRoute } from '@/llm-api/fireworks-config'
import type { MiniMaxUpstream } from '@/llm-api/minimax-request-body'

export type FreeSessionStatus = 'queued' | 'active'

/** Public state returned to CLI clients. Excludes `status: 'none'`, which is
 *  generated by the route handler when `getSessionState` returns null, and
 *  `status: 'superseded'`, which is set directly by `getSessionState` after
 *  comparing the caller's instance id to the stored one. */
export type SessionStateResponse = Exclude<
  FreebuffSessionServerResponse,
  { status: 'none' } | { status: 'superseded' }
>

export interface InternalSessionRow {
  user_id: string
  status: FreeSessionStatus
  active_instance_id: string
  /** Freebuff model id this row is queued for (or locked to, once active). */
  model: string
  access_tier?: FreebuffAccessTier
  /** Sticky Fireworks upstream pin set at admission (see `routeForAdmission`).
   *  Null/absent for queued rows and for models without a serverless backup. */
  fireworks_route?: FireworksRoute | null
  /** Sticky upstream pin for MiniMax-family models that default to the Fireworks
   *  serverless API and fall back to the official MiniMax API on rate limits.
   *  Set reactively to 'minimax' the first time Fireworks rate-limits the
   *  session, then honored for every later request so we never re-pay the
   *  prompt-cache miss. Null/absent → use the default (Fireworks) upstream. */
  minimax_upstream?: MiniMaxUpstream | null
  country_code?: string | null
  cf_country?: string | null
  geoip_country?: string | null
  country_block_reason?: FreebuffCountryBlockReason | null
  ip_privacy_signals?: FreebuffIpPrivacySignal[] | null
  client_ip_hash?: string | null
  country_checked_at?: Date | null
  queued_at: Date
  admitted_at: Date | null
  expires_at: Date | null
  created_at: Date
  updated_at: Date
}

export interface FreeSessionCountryAccessMetadata {
  countryCode: string | null
  cfCountry: string | null
  geoipCountry: string | null
  blockReason: FreebuffCountryBlockReason | null
  ipPrivacySignals: FreebuffIpPrivacySignal[] | null
  clientIpHash: string | null
  checkedAt: Date
}
