[install]
# In CI, skip local linking and pull prebuilt artifacts from npm
linkWorkspacePackages = false

[test]
# Test configuration
preload = ["./test/setup.ts"]

# Module path mappings for Bun runtime
[module]
"@codebuff/common/*" = "./common/src/*"
"@codebuff/billing/*" = "./packages/billing/src/*"
"@codebuff/bigquery/*" = "./packages/bigquery/src/*"
"@codebuff/internal/*" = "./packages/internal/src/*"
"@codebuff/code-map/*" = "./packages/code-map/*"

