[install]
# In CI, skip local linking and pull prebuilt artifacts from npm
linkWorkspacePackages = false

[test]
# Exclude test repositories from test execution to prevent timeouts
exclude = ["evals/test-repos/**"]

