/**
 * Freebuff — Electron main process (the shell side of the
 * Electron-shell + Bun-orchestrator split described in the PRD §6 and README).
 *
 * Electron's main process runs Node, not Bun. To honor "Bun main process"
 * (reuse sdk/ + agent-runtime, which export Bun-targeted TS) the shell spawns
 * the Bun orchestrator as a child process and talks to it over local HTTP/SSE
 * on 127.0.0.1. The renderer is the existing self-contained UI the Bun server
 * serves, so there is no separate renderer build step.
 *
 * Two run modes, see resolveOrchestrator():
 *   - dev: spawn a system `bun` on the TS source (src/app/server.ts).
 *   - packaged: spawn the Bun binary shipped in app resources on the pre-bundled
 *     orchestrator.js (scripts/fetch-bun.ts + scripts/build-orchestrator.ts,
 *     wired into the app via the electron-builder extraResources config). The
 *     user needs no system Bun.
 *
 *   bun --cwd freebuff-desktop run app        # launch from source (dev)
 *   FREEBUFF_TARGET_REPO=/path/to/repo bun --cwd freebuff-desktop run app
 */

const { app, BrowserWindow, Menu, shell, dialog, ipcMain } = require('electron')
const { spawn } = require('node:child_process')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const net = require('node:net')
const http = require('node:http')
const updater = require('./updater.cjs')

// In-app update checker (see updater.cjs). Wired up once boot succeeds; the
// "Check for Updates…" menu item calls through this handle. Null until boot.
/** @type {{ checkNow: (opts?: {interactive?: boolean}) => Promise<void> } | null} */
let updateChecker = null

function checkForUpdatesInteractive() {
  void updateChecker?.checkNow({ interactive: true })
}

const PKG_DIR = path.join(__dirname, '..')
// The packaged app's Info.plist / .ico / .png bundle the right icon, but in dev
// the OS would otherwise show Electron's default icon. Point at our PNG so dev
// looks the same as packaged. The file is generated by scripts/build-icon.ts.
const APP_ICON_PATH = path.join(PKG_DIR, 'build', 'icon.png')

/** @type {import('node:child_process').ChildProcess | null} */
let serverProc = null
/** @type {BrowserWindow | null} */
let mainWindow = null
let shuttingDown = false
// The single trusted origin the renderer is allowed to live at (set in boot()
// once the orchestrator port is known). Navigation / new-window requests to any
// other origin are denied and handed to the system browser, so the preload
// bridge never rides along to an untrusted document.
/** @type {string | null} */
let appOrigin = null
// The URL the renderer loads (orchestrator origin, or the Vite dev server). Held
// at module scope so a macOS dock re-activate can reattach to the live
// orchestrator instead of spawning a second one.
/** @type {string | null} */
let appUrl = null

// Override package.json's "@codebuff/freebuff-desktop" name — that string leaks
// into the macOS app menu, About panel, and Windows taskbar/AppUserModelId.
app.setName('Freebuff')
app.setAppUserModelId('com.freebuff.desktop')
if (process.platform === 'darwin' && app.setAboutPanelOptions) {
  app.setAboutPanelOptions({ name: 'Freebuff' })
}

// How to launch the orchestrator, per run mode. FREEBUFF_BUN_PATH overrides the
// bun binary in either mode (e.g. to test the dev path against a specific bun).
function resolveOrchestrator() {
  if (app.isPackaged) {
    const exe = process.platform === 'win32' ? '.exe' : ''
    const res = process.resourcesPath
    const orchDir = path.join(res, 'orchestrator')
    return {
      bun: process.env.FREEBUFF_BUN_PATH || path.join(res, 'bun', `bun${exe}`),
      args: [path.join(orchDir, 'orchestrator.js')],
      // cwd is the orchestrator dir so the bundled `import 'playwright'` resolves
      // from the node_modules shipped beside it.
      cwd: orchDir,
      uiDir: path.join(orchDir, 'ui'),
      packaged: true,
    }
  }
  return {
    bun: process.env.FREEBUFF_BUN_PATH || 'bun',
    args: [path.join(PKG_DIR, 'src', 'app', 'server.ts')],
    cwd: PKG_DIR,
    // In dev the built dist-ui/ may exist (after `ui:build`); the server falls
    // back to it. When FREEBUFF_DEV_UI is set, the Vite dev server serves the UI.
    uiDir: undefined,
    packaged: false,
  }
}

// Ask the OS for an unused loopback port so two instances never collide.
function findFreePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer()
    srv.unref()
    srv.on('error', reject)
    srv.listen(0, '127.0.0.1', () => {
      const { port } = srv.address()
      srv.close(() => resolve(port))
    })
  })
}

// Poll the orchestrator's /healthz until it answers (or we give up). Using the
// trivial liveness probe instead of /api/state keeps readiness from depending on
// the full engine snapshot serializing.
function waitForServer(port, timeoutMs = 30000) {
  const start = Date.now()
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const req = http.get(
        { host: '127.0.0.1', port, path: '/healthz', timeout: 1500 },
        (res) => {
          res.resume()
          resolve()
        },
      )
      req.on('error', () => {
        if (Date.now() - start > timeoutMs) {
          reject(new Error(`orchestrator did not come up within ${timeoutMs}ms`))
        } else {
          setTimeout(attempt, 300)
        }
      })
      req.on('timeout', () => req.destroy())
    }
    attempt()
  })
}

function startOrchestrator(port) {
  return new Promise((resolve, reject) => {
    const { bun, args, cwd, uiDir, packaged } = resolveOrchestrator()

    // extraResources can lose the executable bit when unpacked; restore it.
    if (packaged && process.platform !== 'win32') {
      try {
        fs.chmodSync(bun, 0o755)
      } catch {
        /* best-effort */
      }
    }

    const env = { ...process.env, PORT: String(port) }
    if (uiDir) env.FREEBUFF_UI_DIR = uiDir
    if (process.env.FREEBUFF_TARGET_REPO) {
      env.TARGET_REPO = process.env.FREEBUFF_TARGET_REPO
    }

    serverProc = spawn(bun, args, {
      cwd,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    serverProc.on('error', (err) => {
      reject(
        new Error(
          `Failed to start the orchestrator with "${bun}": ${err.message}\n\n` +
            (packaged
              ? 'The bundled Bun binary could not be launched.'
              : 'Make sure Bun is installed and on PATH, or set FREEBUFF_BUN_PATH ' +
                'to the bun binary.'),
        ),
      )
    })

    serverProc.stdout.on('data', (d) => process.stdout.write(`[orchestrator] ${d}`))
    serverProc.stderr.on('data', (d) => process.stderr.write(`[orchestrator] ${d}`))

    serverProc.on('exit', (code, signal) => {
      const pid = serverProc?.pid
      serverProc = null
      if (shuttingDown) return
      const detail = signal
        ? `signal ${signal}`
        : `exit code ${code ?? 'unknown'}`
      console.error(`[orchestrator] process ${pid} ended (${detail})`)
      if (code && code !== 0) {
        dialog.showErrorBox(
          'Freebuff orchestrator stopped',
          `The orchestrator process exited unexpectedly (${detail}). ` +
            'See the terminal output for details.',
        )
      }
    })

    waitForServer(port).then(resolve, reject)
  })
}

function stopOrchestrator() {
  shuttingDown = true
  if (serverProc && !serverProc.killed) {
    serverProc.kill('SIGTERM')
    // Hard-stop if it ignores the polite request.
    const proc = serverProc
    setTimeout(() => {
      if (proc && !proc.killed) proc.kill('SIGKILL')
    }, 3000)
  }
}

function loadingPage() {
  // Inline splash shown while the orchestrator boots. Matches the UI's dark +
  // freebuff-lime palette so the transition isn't jarring.
  const html = `<!doctype html><html><head><meta charset="utf-8">
<style>
  html,body{height:100%;margin:0}
  body{display:flex;align-items:center;justify-content:center;flex-direction:column;
    gap:18px;background:#0c0d0f;color:#e6e6e6;
    font:14px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  .dot{width:42px;height:42px;border-radius:50%;
    border:3px solid #1f2937;border-top-color:#7cff3f;animation:spin 0.9s linear infinite}
  .msg{color:#9ca3af}
  @keyframes spin{to{transform:rotate(360deg)}}
</style></head><body>
  <div class="dot"></div>
  <div class="msg">Starting Freebuff orchestrator…</div>
</body></html>`
  return `data:text/html;charset=utf-8,${encodeURIComponent(html)}`
}

/** Whether `url` is same-origin with the trusted app origin (set in boot()).
 *  False before boot resolves the origin, or for an unparseable URL. */
function isAppUrl(url) {
  if (!appOrigin) return false
  try {
    return new URL(url).origin === appOrigin
  } catch {
    return false
  }
}

/** Hand an off-origin link to the system browser — but only http(s), so a
 *  malicious document can't get the OS to launch a file:/custom-scheme URL. */
function openExternalSafely(url) {
  try {
    const { protocol } = new URL(url)
    if (protocol === 'http:' || protocol === 'https:') void shell.openExternal(url)
  } catch {
    /* unparseable URL — ignore */
  }
}

function createWindow() {
  const winOpts = {
    width: 1440,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    backgroundColor: '#0c0d0f',
    title: 'Freebuff',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  }
  if (fs.existsSync(APP_ICON_PATH)) winOpts.icon = APP_ICON_PATH

  mainWindow = new BrowserWindow(winOpts)

  mainWindow.loadURL(loadingPage())

  // New windows: only the trusted app origin may open in-app (with the preload
  // bridge attached); every other URL is denied and opened in the system browser.
  // A broad "any localhost" allow would let a malicious preview link load another
  // local service in a privileged window. http(s) only — never hand the OS a
  // file:/custom-scheme URL.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (isAppUrl(url)) return { action: 'allow' }
    openExternalSafely(url)
    return { action: 'deny' }
  })

  // Top-level navigation: keep the renderer pinned to the app origin so the
  // preload surface can't travel to an untrusted document. Off-origin link
  // clicks are cancelled and sent to the system browser instead.
  mainWindow.webContents.on('will-navigate', (event, url) => {
    if (isAppUrl(url)) return
    event.preventDefault()
    openExternalSafely(url)
  })

  mainWindow.on('closed', () => {
    mainWindow = null
  })

  return mainWindow
}

// Forward a tab command to the renderer, which owns tab state. The renderer also
// handles these via keydown; in Electron the menu accelerator consumes the keys so
// only this IPC path fires (no double-action).
function sendMenuCommand(name) {
  mainWindow?.webContents.send('menu-cmd', name)
}

// Paperclip → native open dialog. Allows files AND folders (multi-select), and
// stats each pick so the renderer can label folders vs. files. Returns [] when the
// user cancels.
ipcMain.handle('dialog:pickAttachments', async () => {
  if (!mainWindow) return []
  const res = await dialog.showOpenDialog(mainWindow, {
    title: 'Attach files or folders',
    buttonLabel: 'Attach',
    properties: ['openFile', 'openDirectory', 'multiSelections', 'treatPackageAsDirectory'],
  })
  if (res.canceled) return []
  return res.filePaths.map((p) => {
    let isDirectory = false
    try {
      isDirectory = fs.statSync(p).isDirectory()
    } catch {
      /* unreadable — treat as a file */
    }
    return { path: p, name: path.basename(p), isDirectory }
  })
})

// Paste-to-attach: a pasted screenshot has no file path, so the renderer hands us
// the raw bytes and we write them to a temp file the attachment pipeline can read.
// `ext` is sanitized to a short alnum token. Returns { path, name } or null.
ipcMain.handle('clipboard:saveImage', async (_e, { bytes, ext }) => {
  try {
    const safeExt = String(ext || 'png').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 8) || 'png'
    const dir = path.join(os.tmpdir(), 'freebuff-desktop-pastes')
    fs.mkdirSync(dir, { recursive: true })
    const file = path.join(dir, `paste-${Date.now()}-${process.pid}.${safeExt}`)
    fs.writeFileSync(file, Buffer.from(bytes))
    return { path: file, name: path.basename(file) }
  } catch {
    return null
  }
})

function buildMenu(reloadApp) {
  const isMac = process.platform === 'darwin'
  // Custom File/Window menus (no default Cmd+W "Close Window" binding) so Cmd+W
  // closes the active TAB, not the window.
  const template = [
    // On mac, build the app menu by hand (instead of `role: 'appMenu'`) so we can
    // slot a native-feeling "Check for Updates…" item right under About.
    ...(isMac
      ? [
          {
            label: app.name,
            submenu: [
              { role: 'about' },
              { label: 'Check for Updates…', click: () => checkForUpdatesInteractive() },
              { type: 'separator' },
              { role: 'services' },
              { type: 'separator' },
              { role: 'hide' },
              { role: 'hideOthers' },
              { role: 'unhide' },
              { type: 'separator' },
              { role: 'quit' },
            ],
          },
        ]
      : []),
    {
      label: 'File',
      submenu: [
        { label: 'New Tab', accelerator: 'CmdOrCtrl+T', click: () => sendMenuCommand('new-tab') },
        {
          label: 'Reopen Closed Tab',
          accelerator: 'CmdOrCtrl+Shift+T',
          click: () => sendMenuCommand('reopen-tab'),
        },
        { label: 'Close Tab', accelerator: 'CmdOrCtrl+W', click: () => sendMenuCommand('close-tab') },
        { type: 'separator' },
        isMac ? { role: 'close', label: 'Close Window', accelerator: 'CmdOrCtrl+Shift+W' } : { role: 'quit' },
      ],
    },
    { role: 'editMenu' },
    {
      label: 'View',
      submenu: [
        { label: 'Reload App', accelerator: 'CmdOrCtrl+R', click: () => reloadApp() },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    { label: 'Window', submenu: [{ role: 'minimize' }, { role: 'zoom' }] },
    // Non-mac has no app menu, so "Check for Updates…" lives under Help.
    ...(isMac
      ? []
      : [
          {
            label: 'Help',
            submenu: [
              { label: 'Check for Updates…', click: () => checkForUpdatesInteractive() },
            ],
          },
        ]),
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

// macOS shows the Dock / Cmd+Tab icon from the running .app bundle, NOT from a
// BrowserWindow's `icon` option (that one is ignored on macOS). In the packaged
// app the bundled icon.icns covers this, but in dev the running bundle is
// Electron's own, so without this the switcher shows the Electron logo. Setting
// the dock icon at runtime fixes both Dock and Cmd+Tab in dev. (The Cmd+Tab
// *name* comes from the bundle's CFBundleName, which has no runtime API — see
// scripts/brand-dev-electron.ts for the dev-only fix.)
function applyDockIcon() {
  if (process.platform !== 'darwin' || !app.dock) return
  try {
    if (fs.existsSync(APP_ICON_PATH)) app.dock.setIcon(APP_ICON_PATH)
  } catch {
    /* best-effort — a bad icon shouldn't stop the app booting */
  }
}

async function boot() {
  applyDockIcon()
  // Reattach, don't respawn: on a macOS dock re-activate the window may have been
  // closed while the orchestrator stayed alive. Spawning another would overwrite
  // serverProc and leak the first. Reuse the live one and just open a window.
  if (serverProc && appUrl) {
    const win = createWindow()
    await win.loadURL(appUrl)
    return
  }
  const win = createWindow()
  try {
    // Dev-UI mode: Vite serves the renderer on 5174 and proxies /api to the Bun
    // orchestrator pinned to 8787. Otherwise the Bun server serves the built SPA.
    const devUi = !!process.env.FREEBUFF_DEV_UI
    const port = devUi ? 8787 : await findFreePort()
    await startOrchestrator(port)
    appUrl = devUi ? 'http://127.0.0.1:5174/' : `http://127.0.0.1:${port}/`
    // Pin the navigation/window-open guards to this exact origin.
    appOrigin = new URL(appUrl).origin
    await win.loadURL(appUrl)
  } catch (err) {
    dialog.showErrorBox('Freebuff failed to start', String(err?.message ?? err))
    app.quit()
    return
  }
  buildMenu(() => mainWindow?.loadURL(appUrl))

  // Start checking for new releases (no-op in dev; see updater.cjs). init() is
  // idempotent, so a macOS dock re-activate that re-runs boot() won't double it.
  updateChecker = updater.init({
    currentVersion: app.getVersion(),
    isPackaged: app.isPackaged,
    getWindow: () => mainWindow,
    // Base URL for the orchestrator so the "install when idle" watcher can poll
    // /api/activity. appUrl always ends in '/'.
    getActivityBase: () => appUrl,
  })
}

// Single-instance lock — a second launch focuses the existing window.
if (!app.requestSingleInstanceLock()) {
  app.quit()
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.focus()
    }
  })

  app.whenReady().then(boot)

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) boot()
  })

  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit()
  })

  app.on('before-quit', stopOrchestrator)
  app.on('will-quit', stopOrchestrator)
}
