/**
 * LLM thread titles for Freebuff Desktop, mirroring the freebuff.com/chat thread
 * titles (`freebuff/web/src/server/chat/title.ts`). When a thread's first message
 * lands the engine shows a prompt-prefix placeholder immediately, then swaps in a
 * short, sensitive-info-free topic title generated by a throwaway single-step
 * agent — one completion, no tools, no subagents.
 *
 * The title runs through the hosted Codebuff SDK client as a normal METERED
 * request (not free mode). Free mode is locked to the freebuff agent hierarchy +
 * CLI system prompt (see web `chat/completions` gate), which a one-off title
 * agent can't satisfy — and chat itself meters its title under a service account
 * rather than running it free. The cost is a single cheap-model completion; any
 * failure (no credits, model error, abort) is swallowed and keeps the
 * placeholder.
 */

import type { AgentDefinition, CodebuffClient } from '@codebuff/sdk'

/** The model only needs the gist; truncate long first messages so the title
 *  call stays cheap and fast. */
const TITLE_INPUT_MAX_CHARS = 2000
/** Max title length — the single source of truth shared with the engine's
 *  prompt-prefix placeholder (see thread-engine `postMessage`). */
export const TITLE_MAX_CHARS = 60

/** What the engine hands the generator to produce a title. */
export interface TitleRequest {
  prompt: string
  model: string
  cwd: string
}

/** Produces a sanitized title (or null to keep the placeholder). Injectable so
 *  tests can stub it without touching the SDK / network. */
export type TitleGenerator = (req: TitleRequest) => Promise<string | null>

/**
 * A throwaway, single-step agent whose only job is to emit a short topic title.
 * No tools, no subagents — one completion. The instructions deliberately keep
 * sensitive details out of the title. Lifted from the chat title agent so the
 * two surfaces produce titles the same way.
 */
function buildTitleAgent(model: string): AgentDefinition {
  return {
    id: 'freebuff-desktop-title',
    displayName: 'Freebuff Desktop Title',
    model: model as AgentDefinition['model'],
    outputMode: 'last_message',
    toolNames: [],
    spawnableAgents: [],
    inputSchema: {
      prompt: { type: 'string', description: "The user's first message." },
    },
    systemPrompt:
      'You generate short, clean titles for chat conversations. You output only the title.',
    instructionsPrompt: `Write a concise title (3-6 words) summarizing the topic of the user's message.

Rules:
- Plain text only: no surrounding quotes, no trailing punctuation, no preamble or explanation.
- Write the title in the same language as the user's message.
- Capitalize it like a headline (when the language uses capitalization).
- Describe what the message is *about*, in general terms. Never copy sensitive personal data into the title — names, emails, phone numbers, addresses, API keys, passwords, or other secrets. Summarize the topic, not the private details.
- If the message is just a greeting or too vague to summarize, output a short generic title like "New thread" (in the message's language).

Output only the title.`,
  } as AgentDefinition
}

/** Cleans up the model's raw output into a single-line, quote-free, length-
 *  bounded title. Returns null when nothing usable is left. */
export function sanitizeTitle(raw: string): string | null {
  let title = raw.replace(/\s+/g, ' ').trim()
  // A "Title:" label the model sometimes prepends despite instructions.
  title = title.replace(/^title:\s*/i, '').trim()
  // Surrounding quotes (straight or curly).
  title = title.replace(/^["'“”‘’]+|["'“”‘’]+$/g, '').trim()
  // Trailing sentence punctuation.
  title = title.replace(/[.!?,;:]+$/g, '').trim()
  if (!title) return null
  return title.slice(0, TITLE_MAX_CHARS)
}

/**
 * The default SDK-backed title generator: runs the throwaway agent on the hosted
 * client as a normal metered request and returns the sanitized title. Errors
 * propagate to the caller, which treats them as "keep the placeholder".
 */
export async function runTitleCompletion(
  client: CodebuffClient,
  req: TitleRequest,
): Promise<string | null> {
  let text = ''
  await client.run({
    agent: buildTitleAgent(req.model),
    prompt: req.prompt.slice(0, TITLE_INPUT_MAX_CHARS),
    // A no-tools, single-step completion: no project scan needed, but cwd is
    // required by the SDK, so point it at the repo root with empty file maps.
    cwd: req.cwd,
    projectFiles: {},
    knowledgeFiles: {},
    maxAgentSteps: 1,
    // The SDK streams the agent's prose as string chunks (mirrors the chat
    // title agent); a single-step, last-message agent has nothing else to emit.
    handleStreamChunk: (chunk: unknown) => {
      if (typeof chunk === 'string') text += chunk
    },
  })
  return sanitizeTitle(text)
}
