/**
 * Regenerate blog/registry.ts imports from posts/*.ts
 * Run: bun freebuff/web/scripts/regenerate-blog-registry.ts
 */
import { readdirSync, writeFileSync } from 'fs'
import { join } from 'path'

const POSTS_DIR = join(import.meta.dir, '../src/lib/blog/posts')
const REGISTRY_PATH = join(import.meta.dir, '../src/lib/blog/registry.ts')

const STATIC_POSTS = [
  'best-free-cli-coding-agents-2026',
  'coding-agent-benchmarks-what-they-miss',
  'free-alternative-to-a0-dev',
  'free-alternative-to-bloom',
  'free-alternative-to-devin',
  'free-alternative-to-gemini-cli',
  'free-alternative-to-heyboss',
  'free-alternative-to-vibecode',
  'free-alternative-to-windsurf',
  'freebuff-in-the-wild-may',
  'freebuff-launch',
  'freebuff-subagents-deep-dive',
  'freebuff-web-launch',
  'freebuff-web-vs-lovable-bolt-replit',
  'side-income-with-freebuff-india',
  'state-of-free-ai-coding-2026',
  'switch-from-cursor-to-freebuff',
  'vly-becomes-freebuff-web',
  'what-developers-are-saying',
  'why-free-coding-agents-won-2026',
]

function slugToImportVar(slug: string): string {
  return slug
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('')
}

const allFiles = readdirSync(POSTS_DIR)
  .filter((f) => f.endsWith('.ts'))
  .map((f) => f.replace(/\.ts$/, ''))
  .sort()

const seoSlugs = new Set(allFiles.filter((s) => !STATIC_POSTS.includes(s)))
const staticSet = new Set(STATIC_POSTS.filter((s) => allFiles.includes(s)))

const imports: string[] = []
for (const slug of allFiles) {
  const varName = slugToImportVar(slug)
  imports.push(`import { post as ${varName} } from './posts/${slug}'`)
}

// Group posts for registry array
const CLI_SEO_IDS = [
  'free-claude-code-cli-coding-agent-alternative-freebuff',
  'free-codex-cli-openai-coding-agent-alternative-freebuff',
  'free-cursor-agent-cli-coding-alternative-freebuff',
  'free-opencode-cli-coding-agent-alternative-freebuff',
  'free-antigravity-cli-coding-agent-alternative-freebuff',
  'free-pi-coding-agent-cli-alternative-freebuff',
  'free-github-copilot-cli-coding-agent-alternative-freebuff',
]

const cliLegacy = [
  'freeAlternativeToWindsurf',
  'freeAlternativeToDevin',
  'freeAlternativeToGeminiCli',
]

const appBuilderComparison = allFiles.filter(
  (s) =>
    s.startsWith('free-') &&
    s.endsWith('-alternative-freebuff') &&
    !CLI_SEO_IDS.includes(s),
)

const cliComparison = CLI_SEO_IDS.filter((s) => allFiles.includes(s))

const cliSavings = allFiles.filter(
  (s) => s.startsWith('save-') && s.includes('-cli-') && s.endsWith('-alternative'),
)
const webSavings = allFiles.filter(
  (s) => s.startsWith('save-') && !cliSavings.includes(s),
)

function ref(slug: string) {
  return slugToImportVar(slug)
}

const registryBody = `import type { Post } from './types'

/**
 * Canonical list of all published blog posts.
 * Regenerated by scripts/regenerate-blog-registry.ts — add static posts there.
 */
const allPosts: Post[] = [
  // Launches
  ${ref('freebuff-launch')},
  ${ref('freebuff-web-launch')},
  ${ref('vly-becomes-freebuff-web')},

  // Comparisons — CLI agents (SEO slugs)
  ${cliComparison.map(ref).join(',\n  ')},
  ${cliLegacy.join(',\n  ')},

  // Comparisons — App builders
  ${appBuilderComparison.map(ref).join(',\n  ')},
  ${['freeAlternativeToA0Dev', 'freeAlternativeToBloom', 'freeAlternativeToHeyboss', 'freeAlternativeToVibecode', ref('freebuff-web-vs-lovable-bolt-replit')].join(',\n  ')},

  // Savings — CLI
  ${cliSavings.map(ref).join(',\n  ')},

  // Savings — App builders
  ${webSavings.map(ref).join(',\n  ')},

  // Guides
  ${ref('best-free-cli-coding-agents-2026')},
  ${ref('switch-from-cursor-to-freebuff')},

  // Research
  ${ref('state-of-free-ai-coding-2026')},
  ${ref('why-free-coding-agents-won-2026')},
  ${ref('coding-agent-benchmarks-what-they-miss')},

  // Engineering
  ${ref('freebuff-subagents-deep-dive')},

  // Community
  ${ref('what-developers-are-saying')},
  ${ref('side-income-with-freebuff-india')},
  ${ref('freebuff-in-the-wild-may')},
]

export function getAllPosts(): Post[] {
  return [...allPosts].sort((a, b) =>
    b.publishedAt.localeCompare(a.publishedAt),
  )
}

export function getPostBySlug(slug: string): Post | undefined {
  return allPosts.find((p) => p.slug === slug)
}

export function getFeaturedPosts(limit = 3): Post[] {
  const featured = getAllPosts().filter((p) => p.featured)
  if (featured.length >= limit) return featured.slice(0, limit)
  const seen = new Set(featured.map((p) => p.slug))
  for (const p of getAllPosts()) {
    if (featured.length >= limit) break
    if (!seen.has(p.slug)) featured.push(p)
  }
  return featured.slice(0, limit)
}

export function getRelatedPosts(slug: string, limit = 3): Post[] {
  const current = getPostBySlug(slug)
  if (!current) return []
  return getAllPosts()
    .filter((p) => p.slug !== slug)
    .map((p) => ({
      post: p,
      score:
        (p.category === current.category ? 2 : 0) +
        p.keywords.filter((k) => current.keywords.includes(k)).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.post)
}

export function getAllCategoriesInUse(): string[] {
  const set = new Set<string>()
  for (const p of allPosts) set.add(p.category)
  return Array.from(set)
}
`

writeFileSync(
  REGISTRY_PATH,
  `${imports.join('\n')}\n\n${registryBody}`,
)

console.log('Registry regenerated with', allFiles.length, 'posts.')
