import { getFreebuffAppUrl } from './freebuff-public-env'

export const siteConfig = {
  title: 'Freebuff — the free coding agent',
  description:
    "Freebuff is the free coding agent: a free CLI coding agent and Freebuff Web, the free way to build full-stack apps. No subscription, no setup, no lock-in. The free alternative to Claude Code, Cursor, Codex, Lovable, Replit, Bolt, Windsurf, and Devin.",
  keywords: () => [
    'Freebuff',
    'Freebuff Web',
    'free coding agent',
    'free CLI coding agent',
    'free AI coding agent',
    'free AI coding assistant',
    'free Claude Code',
    'free Claude Code alternative',
    'free Cursor',
    'free Cursor alternative',
    'free Codex',
    'free OpenAI Codex',
    'free Codex CLI',
    'free Lovable',
    'free Lovable alternative',
    'free Replit',
    'free Replit Agent',
    'free Bolt.new',
    'free Windsurf',
    'free Emergent',
    'free Devin',
    'free v0 alternative',
    'free vly alternative',
    'free full stack app builder',
    'free vibe coding',
    'AI coding assistant',
    'Terminal AI',
    'Codebuff',
    'open source coding agent',
  ],
  url: getFreebuffAppUrl,
}
