/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as abstractor_agent from "../abstractor/agent.js";
import type * as abstractor_routeSync from "../abstractor/routeSync.js";
import type * as activity from "../activity.js";
import type * as admin from "../admin.js";
import type * as adminReferralDashboard from "../adminReferralDashboard.js";
import type * as admin_stats from "../admin_stats.js";
import type * as admin_usage from "../admin_usage.js";
import type * as admin_usage_backfill from "../admin_usage_backfill.js";
import type * as admin_usage_backfill_actions from "../admin_usage_backfill_actions.js";
import type * as aggregates_admin_aggregates from "../aggregates/admin_aggregates.js";
import type * as analytics from "../analytics.js";
import type * as assets from "../assets.js";
import type * as autumn from "../autumn.js";
import type * as build_errors from "../build_errors.js";
import type * as cleanup_deleteSandboxInstances from "../cleanup/deleteSandboxInstances.js";
import type * as codebaseStructure from "../codebaseStructure.js";
import type * as codesandbox_create from "../codesandbox/create.js";
import type * as codesandbox_createProject from "../codesandbox/createProject.js";
import type * as codesandbox_envVars from "../codesandbox/envVars.js";
import type * as codesandbox_export from "../codesandbox/export.js";
import type * as codesandbox_getProjectTheme from "../codesandbox/getProjectTheme.js";
import type * as codesandbox_management from "../codesandbox/management.js";
import type * as codesandbox_projectCrud from "../codesandbox/projectCrud.js";
import type * as codesandbox_updateProjectTheme from "../codesandbox/updateProjectTheme.js";
import type * as codesandbox_versionControl from "../codesandbox/versionControl.js";
import type * as coding_agent_agent_handle_turn from "../coding_agent/agent/handle_turn.js";
import type * as coding_agent_agent_process_codeblocks from "../coding_agent/agent/process/codeblocks.js";
import type * as coding_agent_agent_process_codeblocks_search_replace from "../coding_agent/agent/process/codeblocks_search_replace.js";
import type * as coding_agent_agent_process_compact_messages_xml from "../coding_agent/agent/process/compact_messages_xml.js";
import type * as coding_agent_agent_process_costValidator from "../coding_agent/agent/process/costValidator.js";
import type * as coding_agent_agent_process_cronValidator from "../coding_agent/agent/process/cronValidator.js";
import type * as coding_agent_agent_process_knowledge_prompts from "../coding_agent/agent/process/knowledge_prompts.js";
import type * as coding_agent_agent_process_prompt_assembly_v2 from "../coding_agent/agent/process/prompt_assembly_v2.js";
import type * as coding_agent_agent_process_prompt_pieces from "../coding_agent/agent/process/prompt_pieces.js";
import type * as coding_agent_agent_process_system_prompts from "../coding_agent/agent/process/system_prompts.js";
import type * as coding_agent_agent_runtime_v2 from "../coding_agent/agent/runtime_v2.js";
import type * as coding_agent_agent_tools from "../coding_agent/agent/tools.js";
import type * as coding_agent_agent_wrapper from "../coding_agent/agent/wrapper.js";
import type * as coding_agent_cli_agent_agent_message from "../coding_agent/cli_agent/agent_message.js";
import type * as coding_agent_cli_agent_agent_thread from "../coding_agent/cli_agent/agent_thread.js";
import type * as coding_agent_cli_agent_byokAuth from "../coding_agent/cli_agent/byokAuth.js";
import type * as coding_agent_cli_agent_cli_agent_timeout from "../coding_agent/cli_agent/cli_agent_timeout.js";
import type * as coding_agent_cli_agent_codexAuth from "../coding_agent/cli_agent/codexAuth.js";
import type * as coding_agent_cli_agent_creditTracking from "../coding_agent/cli_agent/creditTracking.js";
import type * as coding_agent_cli_agent_execute from "../coding_agent/cli_agent/execute.js";
import type * as coding_agent_cli_agent_executeClaudeCode from "../coding_agent/cli_agent/executeClaudeCode.js";
import type * as coding_agent_cli_agent_executeCodex from "../coding_agent/cli_agent/executeCodex.js";
import type * as coding_agent_cli_agent_executeFreebuff from "../coding_agent/cli_agent/executeFreebuff.js";
import type * as coding_agent_cli_agent_executeGemini from "../coding_agent/cli_agent/executeGemini.js";
import type * as coding_agent_cli_agent_freebuff_agent_run_mutations from "../coding_agent/cli_agent/freebuff_agent_run_mutations.js";
import type * as coding_agent_cli_agent_freebuff_bundled_agents from "../coding_agent/cli_agent/freebuff_bundled_agents.js";
import type * as coding_agent_cli_agent_queries from "../coding_agent/cli_agent/queries.js";
import type * as coding_agent_cli_agent_shellEscape from "../coding_agent/cli_agent/shellEscape.js";
import type * as coding_agent_cli_agent_streamParser from "../coding_agent/cli_agent/streamParser.js";
import type * as coding_agent_cli_agent_system_prompt from "../coding_agent/cli_agent/system_prompt.js";
import type * as coding_agent_cli_agent_trigger from "../coding_agent/cli_agent/trigger.js";
import type * as coding_agent_cli_agent_workflow from "../coding_agent/cli_agent/workflow.js";
import type * as coding_agent_config_contextLengthPresets from "../coding_agent/config/contextLengthPresets.js";
import type * as coding_agent_context_assembly from "../coding_agent/context/assembly.js";
import type * as coding_agent_context_queries from "../coding_agent/context/queries.js";
import type * as coding_agent_context_types from "../coding_agent/context/types.js";
import type * as coding_agent_cycle from "../coding_agent/cycle.js";
import type * as coding_agent_freebuff_bridge_mutations from "../coding_agent/freebuff_bridge_mutations.js";
import type * as coding_agent_helpers_agent_thread_namer from "../coding_agent/helpers/agent_thread_namer.js";
import type * as coding_agent_helpers_fastReturn from "../coding_agent/helpers/fastReturn.js";
import type * as coding_agent_helpers_refinePrompt from "../coding_agent/helpers/refinePrompt.js";
import type * as coding_agent_helpers_suggestions from "../coding_agent/helpers/suggestions.js";
import type * as coding_agent_helpers_summarizer from "../coding_agent/helpers/summarizer.js";
import type * as coding_agent_helpers_thread_namer from "../coding_agent/helpers/thread_namer.js";
import type * as coding_agent_helpers_tokenizer from "../coding_agent/helpers/tokenizer.js";
import type * as coding_agent_models_cheap_model from "../coding_agent/models/cheap_model.js";
import type * as coding_agent_models_efficient_model from "../coding_agent/models/efficient_model.js";
import type * as coding_agent_models_expensive_model from "../coding_agent/models/expensive_model.js";
import type * as coding_agent_models_fast_model from "../coding_agent/models/fast_model.js";
import type * as coding_agent_models_minimax_model from "../coding_agent/models/minimax_model.js";
import type * as coding_agent_models_opus_model from "../coding_agent/models/opus_model.js";
import type * as coding_agent_models_planning_model from "../coding_agent/models/planning_model.js";
import type * as coding_agent_models_powerful from "../coding_agent/models/powerful.js";
import type * as coding_agent_models_precise_model from "../coding_agent/models/precise_model.js";
import type * as coding_agent_models_secondary_analysis_model from "../coding_agent/models/secondary/analysis_model.js";
import type * as coding_agent_models_secondary_summarizer_model from "../coding_agent/models/secondary/summarizer_model.js";
import type * as coding_agent_models_standard_model from "../coding_agent/models/standard_model.js";
import type * as coding_agent_models_ultra_cheap_model from "../coding_agent/models/ultra_cheap_model.js";
import type * as coding_agent_rateLimiter from "../coding_agent/rateLimiter.js";
import type * as coding_agent_shared_base_knowledge from "../coding_agent/shared/base_knowledge.js";
import type * as coding_agent_shared_geoAccess from "../coding_agent/shared/geoAccess.js";
import type * as coding_agent_shared_triggerGates from "../coding_agent/shared/triggerGates.js";
import type * as coding_agent_terminationThrottle from "../coding_agent/terminationThrottle.js";
import type * as coding_agent_trigger from "../coding_agent/trigger.js";
import type * as community from "../community.js";
import type * as constants from "../constants.js";
import type * as content_moderation from "../content_moderation.js";
import type * as convex_instance from "../convex_instance.js";
import type * as convex_management from "../convex_management.js";
import type * as convex_migration_cli_migrate from "../convex_migration/cli_migrate.js";
import type * as convex_migration_management_api from "../convex_migration/management_api.js";
import type * as convex_migration_status from "../convex_migration/status.js";
import type * as convex_oauth_connections from "../convex_oauth/connections.js";
import type * as convex_oauth_crypto from "../convex_oauth/crypto.js";
import type * as convex_oauth_oauth from "../convex_oauth/oauth.js";
import type * as crons from "../crons.js";
import type * as database_convex from "../database/convex.js";
import type * as daytona_migration_backfill from "../daytona_migration/backfill.js";
import type * as daytona_migration_constants from "../daytona_migration/constants.js";
import type * as daytona_migration_management from "../daytona_migration/management.js";
import type * as daytona_migration_resolve from "../daytona_migration/resolve.js";
import type * as deployment from "../deployment.js";
import type * as deployment_helpers from "../deployment_helpers.js";
import type * as deployment_management from "../deployment_management.js";
import type * as deployment_queries from "../deployment_queries.js";
import type * as domains from "../domains.js";
import type * as earn from "../earn.js";
import type * as editor_filesystem from "../editor/filesystem.js";
import type * as email from "../email.js";
import type * as email_blasts_node from "../email_blasts_node.js";
import type * as entry_point from "../entry_point.js";
import type * as fallback_dist from "../fallback_dist.js";
import type * as fallback_dist_publish from "../fallback_dist_publish.js";
import type * as featureFlags from "../featureFlags.js";
import type * as github_auth from "../github/auth.js";
import type * as github_auth_connections from "../github/auth/connections.js";
import type * as github_auth_index from "../github/auth/index.js";
import type * as github_auth_installation from "../github/auth/installation.js";
import type * as github_auth_oauth from "../github/auth/oauth.js";
import type * as github_config from "../github/config.js";
import type * as github_deployments from "../github/deployments.js";
import type * as github_envExport from "../github/envExport.js";
import type * as github_git_repository from "../github/git/repository.js";
import type * as github_git_secureCredentials from "../github/git/secureCredentials.js";
import type * as github_index from "../github/index.js";
import type * as github_manualSync from "../github/manualSync.js";
import type * as github_octokit from "../github/octokit.js";
import type * as github_repositories from "../github/repositories.js";
import type * as github_services_deploymentService from "../github/services/deploymentService.js";
import type * as github_services_octokitService from "../github/services/octokitService.js";
import type * as github_services_projectService from "../github/services/projectService.js";
import type * as github_sync_cronPostSyncValidator from "../github/sync/cronPostSyncValidator.js";
import type * as github_sync_index from "../github/sync/index.js";
import type * as github_sync_resolution from "../github/sync/resolution.js";
import type * as github_sync_rollback from "../github/sync/rollback.js";
import type * as github_sync_services_backupService from "../github/sync/services/backupService.js";
import type * as github_sync_services_initialSync from "../github/sync/services/initialSync.js";
import type * as github_sync_services_resolutionExecutorService from "../github/sync/services/resolutionExecutorService.js";
import type * as github_sync_services_syncExecutorService from "../github/sync/services/syncExecutorService.js";
import type * as github_sync_services_webhookService from "../github/sync/services/webhookService.js";
import type * as github_sync_status from "../github/sync/status.js";
import type * as github_sync_types from "../github/sync/types.js";
import type * as github_sync_usage from "../github/sync/usage.js";
import type * as github_tokens_index from "../github/tokens/index.js";
import type * as github_tokens_monitoring from "../github/tokens/monitoring.js";
import type * as github_tokens_queries from "../github/tokens/queries.js";
import type * as github_tokens_rotation from "../github/tokens/rotation.js";
import type * as github_tokens_service from "../github/tokens/service.js";
import type * as github_tokens_validation from "../github/tokens/validation.js";
import type * as github_utils_index from "../github/utils/index.js";
import type * as github_utils_octokit from "../github/utils/octokit.js";
import type * as gravity from "../gravity.js";
import type * as gravity_integrations from "../gravity_integrations.js";
import type * as gravity_report from "../gravity_report.js";
import type * as http from "../http.js";
import type * as import_projects from "../import_projects.js";
import type * as integration_auth from "../integration_auth.js";
import type * as integrations from "../integrations.js";
import type * as integrations_add_integration from "../integrations/add_integration.js";
import type * as integrations_research_agent from "../integrations/research_agent.js";
import type * as invites from "../invites.js";
import type * as lib_convex_pricing from "../lib/convex_pricing.js";
import type * as lib_featureAccessControl from "../lib/featureAccessControl.js";
import type * as lib_self_hosted_deployment from "../lib/self_hosted_deployment.js";
import type * as lib_tierLimits from "../lib/tierLimits.js";
import type * as localEnvFix from "../localEnvFix.js";
import type * as memory from "../memory.js";
import type * as messages from "../messages.js";
import type * as migrations from "../migrations.js";
import type * as monitoring from "../monitoring.js";
import type * as org_security from "../org_security.js";
import type * as paused_users from "../paused_users.js";
import type * as pool_management from "../pool_management.js";
import type * as project from "../project.js";
import type * as recommended_integrations from "../recommended_integrations.js";
import type * as referralRewards from "../referralRewards.js";
import type * as referrals from "../referrals.js";
import type * as runtime_errors from "../runtime_errors.js";
import type * as scraped_site_logs from "../scraped_site_logs.js";
import type * as screenshot from "../screenshot.js";
import type * as search from "../search.js";
import type * as services_VersioningService from "../services/VersioningService.js";
import type * as settings from "../settings.js";
import type * as stats from "../stats.js";
import type * as temporaryStream from "../temporaryStream.js";
import type * as thread from "../thread.js";
import type * as ticket_read_state from "../ticket_read_state.js";
import type * as tickets from "../tickets.js";
import type * as tickets_email from "../tickets_email.js";
import type * as tickets_messages from "../tickets_messages.js";
import type * as uiPresets from "../uiPresets.js";
import type * as users from "../users.js";
import type * as users_byok from "../users_byok.js";
import type * as utils_context7 from "../utils/context7.js";
import type * as utils_cross_rank from "../utils/cross_rank.js";
import type * as utils_crypto from "../utils/crypto.js";
import type * as utils_divmagic from "../utils/divmagic.js";
import type * as utils_fast_apply from "../utils/fast_apply.js";
import type * as utils_firecrawl_scrape from "../utils/firecrawl_scrape.js";
import type * as utils_gemini_search from "../utils/gemini_search.js";
import type * as utils_haiku_search from "../utils/haiku_search.js";
import type * as utils_kapa_search from "../utils/kapa_search.js";
import type * as utils_lune_extraction from "../utils/lune_extraction.js";
import type * as utils_performance from "../utils/performance.js";
import type * as utils_perplexity from "../utils/perplexity.js";
import type * as utils_registry from "../utils/registry.js";
import type * as utils_registry_validators from "../utils/registry_validators.js";
import type * as utils_themeUtils from "../utils/themeUtils.js";
import type * as versioning_checkpoint from "../versioning/checkpoint.js";
import type * as webAccess from "../webAccess.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "abstractor/agent": typeof abstractor_agent;
  "abstractor/routeSync": typeof abstractor_routeSync;
  activity: typeof activity;
  admin: typeof admin;
  adminReferralDashboard: typeof adminReferralDashboard;
  admin_stats: typeof admin_stats;
  admin_usage: typeof admin_usage;
  admin_usage_backfill: typeof admin_usage_backfill;
  admin_usage_backfill_actions: typeof admin_usage_backfill_actions;
  "aggregates/admin_aggregates": typeof aggregates_admin_aggregates;
  analytics: typeof analytics;
  assets: typeof assets;
  autumn: typeof autumn;
  build_errors: typeof build_errors;
  "cleanup/deleteSandboxInstances": typeof cleanup_deleteSandboxInstances;
  codebaseStructure: typeof codebaseStructure;
  "codesandbox/create": typeof codesandbox_create;
  "codesandbox/createProject": typeof codesandbox_createProject;
  "codesandbox/envVars": typeof codesandbox_envVars;
  "codesandbox/export": typeof codesandbox_export;
  "codesandbox/getProjectTheme": typeof codesandbox_getProjectTheme;
  "codesandbox/management": typeof codesandbox_management;
  "codesandbox/projectCrud": typeof codesandbox_projectCrud;
  "codesandbox/updateProjectTheme": typeof codesandbox_updateProjectTheme;
  "codesandbox/versionControl": typeof codesandbox_versionControl;
  "coding_agent/agent/handle_turn": typeof coding_agent_agent_handle_turn;
  "coding_agent/agent/process/codeblocks": typeof coding_agent_agent_process_codeblocks;
  "coding_agent/agent/process/codeblocks_search_replace": typeof coding_agent_agent_process_codeblocks_search_replace;
  "coding_agent/agent/process/compact_messages_xml": typeof coding_agent_agent_process_compact_messages_xml;
  "coding_agent/agent/process/costValidator": typeof coding_agent_agent_process_costValidator;
  "coding_agent/agent/process/cronValidator": typeof coding_agent_agent_process_cronValidator;
  "coding_agent/agent/process/knowledge_prompts": typeof coding_agent_agent_process_knowledge_prompts;
  "coding_agent/agent/process/prompt_assembly_v2": typeof coding_agent_agent_process_prompt_assembly_v2;
  "coding_agent/agent/process/prompt_pieces": typeof coding_agent_agent_process_prompt_pieces;
  "coding_agent/agent/process/system_prompts": typeof coding_agent_agent_process_system_prompts;
  "coding_agent/agent/runtime_v2": typeof coding_agent_agent_runtime_v2;
  "coding_agent/agent/tools": typeof coding_agent_agent_tools;
  "coding_agent/agent/wrapper": typeof coding_agent_agent_wrapper;
  "coding_agent/cli_agent/agent_message": typeof coding_agent_cli_agent_agent_message;
  "coding_agent/cli_agent/agent_thread": typeof coding_agent_cli_agent_agent_thread;
  "coding_agent/cli_agent/byokAuth": typeof coding_agent_cli_agent_byokAuth;
  "coding_agent/cli_agent/cli_agent_timeout": typeof coding_agent_cli_agent_cli_agent_timeout;
  "coding_agent/cli_agent/codexAuth": typeof coding_agent_cli_agent_codexAuth;
  "coding_agent/cli_agent/creditTracking": typeof coding_agent_cli_agent_creditTracking;
  "coding_agent/cli_agent/execute": typeof coding_agent_cli_agent_execute;
  "coding_agent/cli_agent/executeClaudeCode": typeof coding_agent_cli_agent_executeClaudeCode;
  "coding_agent/cli_agent/executeCodex": typeof coding_agent_cli_agent_executeCodex;
  "coding_agent/cli_agent/executeFreebuff": typeof coding_agent_cli_agent_executeFreebuff;
  "coding_agent/cli_agent/executeGemini": typeof coding_agent_cli_agent_executeGemini;
  "coding_agent/cli_agent/freebuff_agent_run_mutations": typeof coding_agent_cli_agent_freebuff_agent_run_mutations;
  "coding_agent/cli_agent/freebuff_bundled_agents": typeof coding_agent_cli_agent_freebuff_bundled_agents;
  "coding_agent/cli_agent/queries": typeof coding_agent_cli_agent_queries;
  "coding_agent/cli_agent/shellEscape": typeof coding_agent_cli_agent_shellEscape;
  "coding_agent/cli_agent/streamParser": typeof coding_agent_cli_agent_streamParser;
  "coding_agent/cli_agent/system_prompt": typeof coding_agent_cli_agent_system_prompt;
  "coding_agent/cli_agent/trigger": typeof coding_agent_cli_agent_trigger;
  "coding_agent/cli_agent/workflow": typeof coding_agent_cli_agent_workflow;
  "coding_agent/config/contextLengthPresets": typeof coding_agent_config_contextLengthPresets;
  "coding_agent/context/assembly": typeof coding_agent_context_assembly;
  "coding_agent/context/queries": typeof coding_agent_context_queries;
  "coding_agent/context/types": typeof coding_agent_context_types;
  "coding_agent/cycle": typeof coding_agent_cycle;
  "coding_agent/freebuff_bridge_mutations": typeof coding_agent_freebuff_bridge_mutations;
  "coding_agent/helpers/agent_thread_namer": typeof coding_agent_helpers_agent_thread_namer;
  "coding_agent/helpers/fastReturn": typeof coding_agent_helpers_fastReturn;
  "coding_agent/helpers/refinePrompt": typeof coding_agent_helpers_refinePrompt;
  "coding_agent/helpers/suggestions": typeof coding_agent_helpers_suggestions;
  "coding_agent/helpers/summarizer": typeof coding_agent_helpers_summarizer;
  "coding_agent/helpers/thread_namer": typeof coding_agent_helpers_thread_namer;
  "coding_agent/helpers/tokenizer": typeof coding_agent_helpers_tokenizer;
  "coding_agent/models/cheap_model": typeof coding_agent_models_cheap_model;
  "coding_agent/models/efficient_model": typeof coding_agent_models_efficient_model;
  "coding_agent/models/expensive_model": typeof coding_agent_models_expensive_model;
  "coding_agent/models/fast_model": typeof coding_agent_models_fast_model;
  "coding_agent/models/minimax_model": typeof coding_agent_models_minimax_model;
  "coding_agent/models/opus_model": typeof coding_agent_models_opus_model;
  "coding_agent/models/planning_model": typeof coding_agent_models_planning_model;
  "coding_agent/models/powerful": typeof coding_agent_models_powerful;
  "coding_agent/models/precise_model": typeof coding_agent_models_precise_model;
  "coding_agent/models/secondary/analysis_model": typeof coding_agent_models_secondary_analysis_model;
  "coding_agent/models/secondary/summarizer_model": typeof coding_agent_models_secondary_summarizer_model;
  "coding_agent/models/standard_model": typeof coding_agent_models_standard_model;
  "coding_agent/models/ultra_cheap_model": typeof coding_agent_models_ultra_cheap_model;
  "coding_agent/rateLimiter": typeof coding_agent_rateLimiter;
  "coding_agent/shared/base_knowledge": typeof coding_agent_shared_base_knowledge;
  "coding_agent/shared/geoAccess": typeof coding_agent_shared_geoAccess;
  "coding_agent/shared/triggerGates": typeof coding_agent_shared_triggerGates;
  "coding_agent/terminationThrottle": typeof coding_agent_terminationThrottle;
  "coding_agent/trigger": typeof coding_agent_trigger;
  community: typeof community;
  constants: typeof constants;
  content_moderation: typeof content_moderation;
  convex_instance: typeof convex_instance;
  convex_management: typeof convex_management;
  "convex_migration/cli_migrate": typeof convex_migration_cli_migrate;
  "convex_migration/management_api": typeof convex_migration_management_api;
  "convex_migration/status": typeof convex_migration_status;
  "convex_oauth/connections": typeof convex_oauth_connections;
  "convex_oauth/crypto": typeof convex_oauth_crypto;
  "convex_oauth/oauth": typeof convex_oauth_oauth;
  crons: typeof crons;
  "database/convex": typeof database_convex;
  "daytona_migration/backfill": typeof daytona_migration_backfill;
  "daytona_migration/constants": typeof daytona_migration_constants;
  "daytona_migration/management": typeof daytona_migration_management;
  "daytona_migration/resolve": typeof daytona_migration_resolve;
  deployment: typeof deployment;
  deployment_helpers: typeof deployment_helpers;
  deployment_management: typeof deployment_management;
  deployment_queries: typeof deployment_queries;
  domains: typeof domains;
  earn: typeof earn;
  "editor/filesystem": typeof editor_filesystem;
  email: typeof email;
  email_blasts_node: typeof email_blasts_node;
  entry_point: typeof entry_point;
  fallback_dist: typeof fallback_dist;
  fallback_dist_publish: typeof fallback_dist_publish;
  featureFlags: typeof featureFlags;
  "github/auth": typeof github_auth;
  "github/auth/connections": typeof github_auth_connections;
  "github/auth/index": typeof github_auth_index;
  "github/auth/installation": typeof github_auth_installation;
  "github/auth/oauth": typeof github_auth_oauth;
  "github/config": typeof github_config;
  "github/deployments": typeof github_deployments;
  "github/envExport": typeof github_envExport;
  "github/git/repository": typeof github_git_repository;
  "github/git/secureCredentials": typeof github_git_secureCredentials;
  "github/index": typeof github_index;
  "github/manualSync": typeof github_manualSync;
  "github/octokit": typeof github_octokit;
  "github/repositories": typeof github_repositories;
  "github/services/deploymentService": typeof github_services_deploymentService;
  "github/services/octokitService": typeof github_services_octokitService;
  "github/services/projectService": typeof github_services_projectService;
  "github/sync/cronPostSyncValidator": typeof github_sync_cronPostSyncValidator;
  "github/sync/index": typeof github_sync_index;
  "github/sync/resolution": typeof github_sync_resolution;
  "github/sync/rollback": typeof github_sync_rollback;
  "github/sync/services/backupService": typeof github_sync_services_backupService;
  "github/sync/services/initialSync": typeof github_sync_services_initialSync;
  "github/sync/services/resolutionExecutorService": typeof github_sync_services_resolutionExecutorService;
  "github/sync/services/syncExecutorService": typeof github_sync_services_syncExecutorService;
  "github/sync/services/webhookService": typeof github_sync_services_webhookService;
  "github/sync/status": typeof github_sync_status;
  "github/sync/types": typeof github_sync_types;
  "github/sync/usage": typeof github_sync_usage;
  "github/tokens/index": typeof github_tokens_index;
  "github/tokens/monitoring": typeof github_tokens_monitoring;
  "github/tokens/queries": typeof github_tokens_queries;
  "github/tokens/rotation": typeof github_tokens_rotation;
  "github/tokens/service": typeof github_tokens_service;
  "github/tokens/validation": typeof github_tokens_validation;
  "github/utils/index": typeof github_utils_index;
  "github/utils/octokit": typeof github_utils_octokit;
  gravity: typeof gravity;
  gravity_integrations: typeof gravity_integrations;
  gravity_report: typeof gravity_report;
  http: typeof http;
  import_projects: typeof import_projects;
  integration_auth: typeof integration_auth;
  integrations: typeof integrations;
  "integrations/add_integration": typeof integrations_add_integration;
  "integrations/research_agent": typeof integrations_research_agent;
  invites: typeof invites;
  "lib/convex_pricing": typeof lib_convex_pricing;
  "lib/featureAccessControl": typeof lib_featureAccessControl;
  "lib/self_hosted_deployment": typeof lib_self_hosted_deployment;
  "lib/tierLimits": typeof lib_tierLimits;
  localEnvFix: typeof localEnvFix;
  memory: typeof memory;
  messages: typeof messages;
  migrations: typeof migrations;
  monitoring: typeof monitoring;
  org_security: typeof org_security;
  paused_users: typeof paused_users;
  pool_management: typeof pool_management;
  project: typeof project;
  recommended_integrations: typeof recommended_integrations;
  referralRewards: typeof referralRewards;
  referrals: typeof referrals;
  runtime_errors: typeof runtime_errors;
  scraped_site_logs: typeof scraped_site_logs;
  screenshot: typeof screenshot;
  search: typeof search;
  "services/VersioningService": typeof services_VersioningService;
  settings: typeof settings;
  stats: typeof stats;
  temporaryStream: typeof temporaryStream;
  thread: typeof thread;
  ticket_read_state: typeof ticket_read_state;
  tickets: typeof tickets;
  tickets_email: typeof tickets_email;
  tickets_messages: typeof tickets_messages;
  uiPresets: typeof uiPresets;
  users: typeof users;
  users_byok: typeof users_byok;
  "utils/context7": typeof utils_context7;
  "utils/cross_rank": typeof utils_cross_rank;
  "utils/crypto": typeof utils_crypto;
  "utils/divmagic": typeof utils_divmagic;
  "utils/fast_apply": typeof utils_fast_apply;
  "utils/firecrawl_scrape": typeof utils_firecrawl_scrape;
  "utils/gemini_search": typeof utils_gemini_search;
  "utils/haiku_search": typeof utils_haiku_search;
  "utils/kapa_search": typeof utils_kapa_search;
  "utils/lune_extraction": typeof utils_lune_extraction;
  "utils/performance": typeof utils_performance;
  "utils/perplexity": typeof utils_perplexity;
  "utils/registry": typeof utils_registry;
  "utils/registry_validators": typeof utils_registry_validators;
  "utils/themeUtils": typeof utils_themeUtils;
  "versioning/checkpoint": typeof versioning_checkpoint;
  webAccess: typeof webAccess;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  migrationWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"migrationWorkpool">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  allUsersAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"allUsersAggregate">;
  userActivityAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"userActivityAggregate">;
  activeUsersByDayAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"activeUsersByDayAggregate">;
  usersByRoleAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByRoleAggregate">;
  usersByTierAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByTierAggregate">;
  usersByDayAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByDayAggregate">;
  allProjectsAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"allProjectsAggregate">;
  projectsByDayAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"projectsByDayAggregate">;
  allConvexInstancesAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"allConvexInstancesAggregate">;
  pausedProjectsByActiveAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"pausedProjectsByActiveAggregate">;
  pausedUsersByActiveAggregate: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"pausedUsersByActiveAggregate">;
};
