#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(scriptDir, '..', '..')
const outputPath = join(
  repoRoot,
  'cli',
  'src',
  'data',
  'initial-agent-type-sources.generated.ts',
)

const typeFiles = {
  agentDefinitionSource: join(
    repoRoot,
    'common',
    'src',
    'templates',
    'initial-agents-dir',
    'types',
    'agent-definition.ts',
  ),
  toolsSource: join(
    repoRoot,
    'common',
    'src',
    'templates',
    'initial-agents-dir',
    'types',
    'tools.ts',
  ),
  utilTypesSource: join(
    repoRoot,
    'common',
    'src',
    'templates',
    'initial-agents-dir',
    'types',
    'util-types.ts',
  ),
} as const

const exports = Object.entries(typeFiles)
  .map(
    ([exportName, sourcePath]) =>
      `export const ${exportName} = ${JSON.stringify(readFileSync(sourcePath, 'utf8'))}`,
  )
  .join('\n\n')

const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 * Generated by scripts/generate-init-type-sources.ts so compiled binaries do
 * not depend on runtime text-import support.
 */

${exports}
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, output)
console.log(`Generated ${outputPath}`)
