/**
 * SEO keywords for DesignArena competitor blog posts.
 * Tuned to real search queries — include product URLs and disambiguators
 * for common names (Canva, Mocha, Aura, Orchids, etc.).
 */

export const comparisonKeywordsById: Record<string, string[]> = {
  anything: [
    'free anything alternative',
    'anything.com ai app builder',
    'createanything.com free',
    'anything ai app builder',
    'create anything ai builder',
    'anything.com alternative free',
    'anything vs lovable',
    'anything app builder pricing',
    'anything vs freebuff',
  ],
  aura: [
    'free aura.build alternative',
    'aura.build ai website builder',
    'aura ai landing page builder',
    'aura.build free',
    'aura ai website builder',
    'aura build ai',
    'aura ai design tool free',
    'aura vs lovable',
    'aura.build pricing alternative',
    'aura vs freebuff',
  ],
  base44: [
    'free base44 alternative',
    'base44 ai app builder',
    'base44.com alternative',
    'base44 internal tool builder',
    'base44 free',
    'base44 vs freebuff',
    'free internal tool builder',
  ],
  bolt: [
    'free bolt.new',
    'bolt.new alternative',
    'bolt.new ai app builder free',
    'bolt.new free',
    'stackblitz bolt alternative',
    'bolt.new vs freebuff',
    'free in browser app generator',
  ],
  canva: [
    'free canva code alternative',
    'canva code ai',
    'canva code generator',
    'canva ai code generator',
    'canva ai app builder',
    'canva code free',
    'canva code alternative',
    'canva code 2.0',
    'canva interactive app builder',
    'build app with canva code',
    'canva code pricing',
    'canva code vs lovable',
    'canva code vs freebuff',
  ],
  cosmic: [
    'free cosmic.new alternative',
    'cosmic.new ai app builder',
    'cosmic.new free',
    'cosmic new ai builder',
    'cosmic ai saas builder',
    'cosmic.new pricing',
    'cosmic.new vs lovable',
    'cosmic.new not cosmicjs',
    'cosmic.new vs freebuff',
  ],
  emergent: [
    'free emergent alternative',
    'emergent.sh free',
    'emergent.sh ai app builder',
    'emergent ai app builder',
    'emergent vs freebuff',
    'free ai app generator',
  ],
  'figma-make': [
    'free figma make alternative',
    'figma make ai app builder',
    'figma ai app builder',
    'figma make free',
    'figma make pricing',
    'figma prompt to app',
    'figma make vs lovable',
    'figma make vs freebuff',
  ],
  floot: [
    'free floot alternative',
    'floot ai app builder',
    'floot.com alternative',
    'floot free',
    'floot vs freebuff',
  ],
  'google-ai-studio': [
    'free google ai studio alternative',
    'google ai studio build app',
    'aistudio.google.com app builder',
    'gemini app builder free',
    'build app with gemini',
    'google ai studio app builder free',
    'gemini ai app builder',
    'google ai studio vs lovable',
    'google ai studio vs freebuff',
  ],
  lovable: [
    'free lovable alternative',
    'lovable.dev free',
    'lovable ai app builder free',
    'lovable free',
    'lovable.dev alternative',
    'free vibe coding',
    'lovable vs freebuff',
  ],
  macaly: [
    'free macaly alternative',
    'macaly ai app builder',
    'macaly.com ai website builder',
    'macaly app builder free',
    'macaly free',
    'macaly vs freebuff',
  ],
  'magic-patterns': [
    'free magic patterns alternative',
    'magic patterns ai ui generator',
    'magicpatterns.com alternative',
    'magic patterns prototype builder',
    'magic patterns free',
    'magic patterns vs figma',
    'magic patterns vs freebuff',
  ],
  mocha: [
    'free mocha ai app builder alternative',
    'getmocha.com alternative',
    'getmocha ai app builder',
    'mocha ai app builder',
    'mocha app builder free',
    'mocha srcbook alternative',
    'mocha shutdown alternative',
    'migrate from getmocha',
    'mocha vs lovable',
    'mocha vs bolt',
    'mocha vs freebuff',
  ],
  orchids: [
    'free orchids ai app builder',
    'orchids ai app builder',
    'orchids.app free',
    'orchids ai free',
    'orchids v2 ai',
    'orchids ai website builder',
    'orchids no code app builder',
    'orchids ai code generator',
    'orchids vs lovable',
    'orchids vs bolt',
    'orchids vs freebuff',
  ],
  replit: [
    'free replit alternative',
    'replit agent free',
    'replit design mode free',
    'replit ai app builder',
    'replit core free',
    'replit vs freebuff',
    'free online ide with agent',
  ],
  'same-new': [
    'free same.new alternative',
    'same.new ai app builder',
    'same ai app builder',
    'same.new free',
    'same.new pricing',
    'same.new vs lovable',
    'same.new vs freebuff',
  ],
  v0: [
    'free v0 alternative',
    'v0.app free',
    'v0.dev alternative',
    'vercel v0 free',
    'v0 ai app builder',
    'v0 ui generator free',
    'v0 vercel pricing',
    'v0 full stack alternative',
    'v0 vs lovable',
    'v0 vs freebuff',
  ],

  // —— CLI coding agents ——
  'claude-code': [
    'free claude code cli',
    'free claude code alternative',
    'claude code cli free',
    'claude code alternative',
    'anthropic claude code cli',
    'claude code vs freebuff',
    'free cli coding agent',
    'claude code pro pricing alternative',
  ],
  codex: [
    'free codex cli',
    'codex cli alternative',
    'openai codex cli free',
    'chatgpt codex cli alternative',
    'codex cli vs freebuff',
    'free openai coding agent cli',
    'gpt codex cli alternative',
  ],
  opencode: [
    'free opencode cli',
    'opencode cli alternative',
    'sst opencode free',
    'opencode coding agent',
    'opencode vs freebuff',
    'free open source cli coding agent',
    'opencode cli byok alternative',
  ],
  cursor: [
    'free cursor agent cli',
    'cursor agent alternative',
    'cursor cli coding agent',
    'cursor pro alternative free',
    'cursor agent vs freebuff',
    'free cursor alternative',
    'cursor.com agent free',
  ],
  antigravity: [
    'free antigravity cli',
    'antigravity cli alternative',
    'google antigravity cli',
    'antigravity coding agent free',
    'antigravity vs freebuff',
    'free agentic ide alternative',
    'antigravity cli gemini alternative',
  ],
  pi: [
    'free pi coding agent',
    'pi cli coding agent',
    'pi-coding-agent alternative',
    'pi-mono cli free',
    'pi harness coding agent',
    'pi agent vs claude code',
    'pi coding agent vs freebuff',
    'mario zechner pi agent',
  ],
  'github-copilot-cli': [
    'free github copilot cli',
    'github copilot cli alternative',
    'copilot cli coding agent',
    'github copilot cli pricing',
    'copilot cli vs freebuff',
    'free copilot cli alternative',
    'github copilot agent cli free',
  ],
}

/** Savings posts: intent keywords + top comparison terms (deduped). */
export function savingsKeywordsFor(id: string): string[] {
  const base = [
    `${id} savings`,
    `switch from ${id} to freebuff`,
    `${id} pricing`,
    `${id} vs freebuff cost`,
    `free ${id} alternative`,
  ]
  const comparison = comparisonKeywordsById[id] ?? []
  return [...new Set([...base, ...comparison])]
}

export function formatKeywordsArray(keywords: string[], indent = '  '): string {
  const itemIndent = indent + '  '
  const lines = keywords.map((k) => `${itemIndent}'${k.replace(/'/g, "\\'")}',`)
  return `keywords: [\n${lines.join('\n')}\n${indent}],`
}
