name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Typecheck all packages
        run: bun run typecheck

      - name: Get Credentials
        run: echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Run npm-app tests
        run: cd npm-app && bun test
        
      - name: Run backend tests
        run: cd backend && bun test
        
      - name: Run common tests
        run: cd common && bun test
