name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build dependencies
        run: |
          bun run --cwd common build
          bun run --cwd packages/billing build

      - name: Typecheck all packages
        run: bun run typecheck

      - name: Get Credentials
        run: echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Run npm-app tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: CODEBUFF_GITHUB_ACTIONS=true cd npm-app && bun test

      - name: Run backend tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: CODEBUFF_GITHUB_ACTIONS=true cd backend && bun test

      - name: Run common tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: CODEBUFF_GITHUB_ACTIONS=true cd common && bun test
