name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type (patch, minor, major, or specific version like 1.2.3)'
        required: true
        type: string
        default: 'patch'
      package_name:
        description: 'Target package name (e.g., codebuff, codecane, or any test name)'
        required: false
        default: 'codebuff'
        type: string

permissions:
  contents: write

jobs:
  # First job: Calculate new version and update package files
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      # Cache Bun downloads for speed
      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}


      # Cache Bun build artifacts
      - name: Cache Bun build
        uses: actions/cache@v4
        with:
          path: |
            npm-app/.bun-build
            npm-app/node_modules/.cache
          key: ${{ runner.os }}-${{ matrix.target }}-bun-build-${{ hashFiles('npm-app/src/**/*.ts', 'npm-app/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-bun-build-
            ${{ runner.os }}-bun-build-

      # Cache dependencies for speed
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ hashFiles('**/bun.lockb') }}
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Calculate and update version and package names
        id: bump_version
        run: |
          cd npm-app
          
          # Get current version from main package
          CURRENT_VERSION=$(node -p "require('./packages/codebuff/package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Calculate new version
          VERSION_TYPE="${{ inputs.version_type }}"
          if [[ "$VERSION_TYPE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            NEW_VERSION="$VERSION_TYPE"
          else
            IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            PATCH=${VERSION_PARTS[2]}
            
            case "$VERSION_TYPE" in
              "major")
                NEW_VERSION="$((MAJOR + 1)).0.0"
                ;;
              "minor")
                NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
                ;;
              "patch"|*)
                NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
                ;;
            esac
          fi
          
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Update package names if needed
          PACKAGE_NAME="${{ inputs.package_name }}"
          if [[ "$PACKAGE_NAME" != "codebuff" ]]; then
            echo "Updating package names to: $PACKAGE_NAME"
            bun run scripts/update-package-names.js "$PACKAGE_NAME"
          fi
          
          # Update all package.json files with new version
          for package_dir in packages/*/; do
            if [ -f "$package_dir/package.json" ]; then
              echo "Updating $package_dir/package.json to version $NEW_VERSION"
              node -e "
                const fs = require('fs');
                const pkg = JSON.parse(fs.readFileSync('$package_dir/package.json', 'utf8'));
                pkg.version = '$NEW_VERSION';
                if (pkg.optionalDependencies) {
                  for (const dep in pkg.optionalDependencies) {
                    pkg.optionalDependencies[dep] = '^$NEW_VERSION';
                  }
                }
                fs.writeFileSync('$package_dir/package.json', JSON.stringify(pkg, null, 2) + '\n');
              "
            fi
          done
          
      - name: Upload updated packages
        uses: actions/upload-artifact@v4
        with:
          name: updated-packages
          path: npm-app/packages/

  build-binaries:
    needs: prepare-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
            package: codebuff-linux-x64
            binary: codebuff
            bun_target: bun-linux-x64
            platform: linux
            arch: x64
          - os: ubuntu-latest
            target: linux-arm64
            package: codebuff-linux-arm64
            binary: codebuff
            bun_target: bun-linux-arm64
            platform: linux
            arch: arm64
          - os: macos-13
            target: darwin-x64
            package: codebuff-darwin-x64
            binary: codebuff
            bun_target: bun-darwin-x64
            platform: darwin
            arch: x64
          - os: macos-14
            target: darwin-arm64
            package: codebuff-darwin-arm64
            binary: codebuff
            bun_target: bun-darwin-arm64
            platform: darwin
            arch: arm64
          - os: windows-latest
            target: win32-x64
            package: codebuff-win32-x64
            binary: codebuff.exe
            bun_target: bun-windows-x64
            platform: win32
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download updated packages
        uses: actions/download-artifact@v4
        with:
          name: updated-packages
          path: npm-app/packages/

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      # Cache dependencies for speed
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ hashFiles('**/bun.lockb') }}
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        env:
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        shell: bash
        run: |
          VAR_NAMES=$(node scripts/generate-ci-env.js)
          echo "$SECRETS_CONTEXT" | jq -r --argjson vars "$VAR_NAMES" '
            to_entries | .[] | select(.key as $k | $vars | index($k)) | .key + "=" + .value
          ' >> $GITHUB_ENV
          echo "CODEBUFF_GITHUB_ACTIONS=true" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CB_ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "CODEBUFF_GITHUB_TOKEN=${{ secrets.CODEBUFF_GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build binary
        run: bun run scripts/build-binary.js
        working-directory: npm-app
        shell: bash
        env:
          VERBOSE: true
          OVERRIDE_TARGET: ${{ matrix.bun_target }}
          OVERRIDE_PLATFORM: ${{ matrix.platform }}
          OVERRIDE_ARCH: ${{ matrix.arch }}

      - name: Test binary
        run: |
          cd npm-app/bin
          echo "Testing binary..."
          # Only test if we're building for the native architecture
          if [[ "${{ matrix.platform }}" == "linux" && "${{ matrix.arch }}" == "arm64" && "${{ runner.arch }}" != "ARM64" ]]; then
            echo "Skipping test for cross-compiled ARM64 binary"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            ./codebuff.exe --version
          else
            ./codebuff --version
          fi
        shell: bash

      - name: Copy binary to platform package
        run: |
          mkdir -p npm-app/packages/${{ matrix.package }}
          cp npm-app/bin/${{ matrix.binary }} npm-app/packages/${{ matrix.package }}/
        shell: bash

      - name: Upload platform package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: npm-app/packages/${{ matrix.package }}/

  # Publish all platform packages only after all builds succeed
  publish-platform-packages:
    needs: [prepare-release, build-binaries]
    strategy:
      matrix:
        package: [codebuff-linux-x64, codebuff-linux-arm64, codebuff-darwin-x64, codebuff-darwin-arm64, codebuff-win32-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Download platform package
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ${{ matrix.package }}/

      - name: Set up Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Publish platform package
        run: |
          cd ${{ matrix.package }}
          npm publish --access public

  # Publish the stub package last, once all platform binaries are live
  publish-main-package:
    needs: [prepare-release, publish-platform-packages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download updated packages
        uses: actions/download-artifact@v4
        with:
          name: updated-packages
          path: npm-app/packages/

      - name: Set up Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Publish main stub package
        run: |
          cd npm-app/packages/codebuff
          npm publish --access public

  # Commit version changes only after successful publishing
  commit-release:
    needs: [prepare-release, publish-platform-packages, publish-main-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download updated packages
        uses: actions/download-artifact@v4
        with:
          name: updated-packages
          path: npm-app/packages/

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push version bump
        run: |
          git add npm-app/packages/*/package.json
          if [ -f "npm-app/package.release.json" ]; then
            git add npm-app/package.release.json
          fi
          git commit -m "Bump version to ${{ needs.prepare-release.outputs.new_version }}"
          git push

      - name: Create and push tag
        run: |
          git tag "v${{ needs.prepare-release.outputs.new_version }}"
          git push origin "v${{ needs.prepare-release.outputs.new_version }}"
